- hosts: compute

  vars:
    ansible_user: "opc"
    ansible_become: "yes"
    ansible_become_method: "sudo"
    ansible_private_key_file: "~/.corc/ssh/id_rsa"

  roles:
    - { role: rasmunk/common/tools, become: yes }
    - { role: rasmunk/services/jupyter/sshspawner, become: yes }
    - { role: rasmunk/services/jupyter/jupyterlab, become: yes }


  # Setup the target to accept the host key of the JupyterHub server
  tasks:
    - name: install the host key of the JupyterHub server
      known_hosts:
        name: "{{ jupyterhub.server_public_ip }}"
        path: /etc/ssh/ssh_known_hosts
        key: "{{ jupyterhub.server_host_key }}"
        state: present
