environments:
  pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - multiplespawner
pipelines:
  multiplespawner:
    group: pypi_package
    locking: off
    materials:
      multiplespawner_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/multiplespawner.git
        branch: master
        destination: multiplespawner
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: multiplespawner
      TEST_DIRECTORY: multiplespawner
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package