- hosts: compute
  # Git clone the sshspawner
  vars:
    ansible_python_interpreter: /usr/bin/python
    python3_path: /usr/bin/python3
    pip3_path: /usr/bin/pip3

    sshspawner:
      name: "sshspawner"
      src: "/tmp/sshspawner"
      repo: "https://github.com/NERSC/sshspawner.git"
      src_getport: "/tmp/sshspawner/scripts/get_port.py"
      dest_getport: "/usr/local/bin/get_port.py"

  tasks:
  - name: install packages
    yum:
      state: present
      name:
        - git
        - python3

  - name: install python packages
    pip:
      name:
        - jupyter
      extra_args: --user
      executable: "{{ pip3_path }}"

  - name: "clone {{ sshspawner.name }}"
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      clone: yes
    with_items:
      - { repo: "{{ sshspawner.repo }}", dest: "{{ sshspawner.src }}" }

  - name: "install {{ sshspawner.name }}"
    shell:
      cmd: "{{ python3_path }} setup.py install"
      chdir: "{{ sshspawner.src }}"

  - name: move the get_port.py to the default location
    command: "cp {{ item.src }} {{ item.dest }}"
    with_items:
      - { src: "{{ sshspawner.src_getport }}", dest: "{{ sshspawner.dest_getport }}" }